import numpy as np

# layerThickness = 0.2
LAYER_THICKNESS = 0.2
NOZZLE_SIZE = 0.4  # for calculation extrusion
LINE_WIDTH = 0.4  # for caluculating the offset for polygons
EXTRUDER_TEMPERATURE = 210
BED_TEMPERATURE = 70
RETRACTION_LENGTH = 4.5
FILAMENT_DIAMETER = 2.85
SHELL_SIZE = 3
FIRST_LAYER_OFFSET = 0
MIN_RETRACTION_DISTANCE = 5
USE_ADAPTIVE_SLICING = False
UP_SKINS_COUNT = 4
DOWN_SKINS_COUNT = 3


# travel speed
Z_MOVEMENT_SPEED = 9000
IN_AIR_SPEED = 9000
RETRACTION_SPEED = 2400
SPEED_RATE = 1800
INFILL_SPEED = 1800
SKIN_SPEED = 1800
RAFT_SPEED = 1800
BOUNDARY_SPEED = 1800
INNER_BOUNDARY_SPEED = 1800
HOLE_SPEED = 1800
SUPPORT_SPEED = 1800

# fan speed
HAS_CONTROLLABLE_FAN_SPEED = True
DEFAULT_FAN_SPEED = 1
EXTERIOR_FAN_SPEED = 1
BRIDGE_FAN_SPEED = 1
INTERIOR_FAN_SPEED = 1
SUPPORT_FAN_SPEED = 1
SKIRT_FAN_SPEED = 1
RAFT_FAN_SPEED = 1

# support
USE_SUPPORT = True
SUPPORT_SAMPLING_DISTANCE = 2
LINK_THRESHOLD = 5*np.sqrt(2*(SUPPORT_SAMPLING_DISTANCE**2))
BED_SUPPORT_STRENGTHEN_OFFSET_NUMBER = 2
BED_SUPPORT_STRENGTHEN_LAYER_NUMBER = 2 # needs to be at least one
SUPPORT_OVERHANG_ANGLE = 85
SUPPORT_HORIZONTAL_OFFSET_FROM_PARTS = 0.5
SUPPORT_AREA_ENLARGE_VALUE = 0.4
ONE_EMPTY_LAYER_BETWEEN_SUPPORT_AND_MODEL = True
SUPPORT_LINE_ANGLE = 0
DOES_REMOVE_SMALL_AREA = True
SMALL_AREA = 5
BED_SUPPORT_STRENGTHEN_NUMBER = 3

PLATFORM_BOUND = "brim"
PLATFORM_BOUND_COUNT = 3
RAFT = False # RAFT very slow
RAFT_LAYER_THICKNESS = 0.15
EXTRUSION_MULTIPLIER = 1.1
INITIAL_EXTRUSION = 0.2
TO_FILE = False

# outline / boundary
OUTLINE_OUTSIDE_IN = False
BOUNDARY_STARTS_CLOSE_TO_POINT = [150, 300]
INNER_BOUNDARY_COAST_AT_END_LENGTH = 0.5
OUTER_BOUNDARY_COAST_AT_END_LENGTH = 0
BOUNDARY_RETRACTION_INSIDE = True

# new
RETRACTION_AT_CHANGE_LAYER = True

# first layer
FIRST_LAYER_LINE_WIDTH = 0.42
FIRST_LAYER_INFILL_SPEED = 750
FIRST_LAYER_SKIN_SPEED = 750
FIRST_LAYER_HOLE_SPEED = 750
FIRST_LAYER_SUPPORT_SPEED = 750
FIRST_LAYER_RAFT_SPEED = 750
FIRST_LAYER_BOUNDARY_SPEED = 750
FIRST_LAYER_INNER_BOUNDARY_SPEED = 750
FIRST_LAYER_THICKNESS = 0.2 # only allow maximun two decimal places